# -*- coding: utf-8 -*-
"""cse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeWtk4ily6s4Mai_KPNq3XVp5lKNoTrQ
"""

from transformers import pipeline
import requests

# Load the fact-checking pipeline
fact_checking_pipeline = pipeline("zero-shot-classification")

# Define the claim to fact-check
claim = "Climate change is a myth."

# Define potential labels for fact-checking
candidate_labels = ["True","Half True", "Half False", "False"]

# Perform fact-checking using HiSS
hiss_prompt = f"Is the following claim true or false?: '{claim}'"
hiss_results = fact_checking_pipeline(hiss_prompt, candidate_labels)

# Perform fact-checking using a generic prompt
generic_prompt = "Is the following claim true or false?"
generic_results = fact_checking_pipeline(claim, candidate_labels)

# Perform a Google search for the claim using Google Programmable Search Engine (CSE)
api_key = "72355baad44d94c7e"
search_engine_id = "FactChecking"
search_url = f"https://www.googleapis.com/customsearch/v1?q={claim}&key={api_key}&cx={search_engine_id}"
response = requests.get(search_url)
search_results = response.json().get("items", [])

# Print out the search results
print("Google Search Results:")
for idx, result in enumerate(search_results, 1):
    print(f"{idx}. {result['title']}: {result['link']}")

# Print out the fact-checking results
print("\nResults using HiSS prompt:")
for label, score in zip(hiss_results["labels"], hiss_results["scores"]):
    print(f"{label}: {score:.2f}")

print("\nResults using generic prompt:")
for label, score in zip(generic_results["labels"], generic_results["scores"]):
    print(f"{label}: {score:.2f}")