# -*- coding: utf-8 -*-
"""googlesearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyeDYKC1yNPWRyo1L1CycT0hbmr_Wmsy
"""

from transformers import pipeline
from googlesearch import search

# Load the fact-checking pipeline
fact_checking_pipeline = pipeline("zero-shot-classification")

# Define the claim to fact-check
claim = "Climate change is a mith."

# Define potential labels for fact-checking
candidate_labels = ["True","Half True", "Hlaf False", "False"]

# Perform fact-checking using HiSS
hiss_prompt = f"Is the following claim true or false?: '{claim}'"
hiss_results = fact_checking_pipeline(hiss_prompt, candidate_labels)

# Perform fact-checking using a generic prompt
generic_prompt = "Is the following claim true or false?"
generic_results = fact_checking_pipeline(claim, candidate_labels)

# Perform a Google search for the claim
search_results = list(search(claim, num=5, stop=5, pause=2))  # Adjust parameters as needed

# Print out the search results
print("Google Search Results:")
for idx, result in enumerate(search_results, 1):
    print(f"{idx}. {result}")

# Print out the fact-checking results
print("\nResults using HiSS prompt:")
for label, score in zip(hiss_results["labels"], hiss_results["scores"]):
    print(f"{label}: {score:.2f}")

print("\nResults using generic prompt:")
for label, score in zip(generic_results["labels"], generic_results["scores"]):
    print(f"{label}: {score:.2f}")